---
- name: Create wp-config.php with database credentials
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wordpress/wp-config.php
  become: yes

- name: Ensure the /var/www/wordpress/wordpress directory exists
  file:
    path: /var/www/wordpress/wordpress
    state: directory
    mode: '0755'
  become: yes

- name: Set correct ownership and permissions for wp-config.php
  file:
    path: /var/www/wordpress/wordpress/wp-config.php
    owner: apache
    group: apache
    mode: '0644'
  become: yes





#*******************88



# Download WP-CLI
- name: Download WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /tmp/wp-cli.phar
  become: yes

# Make WP-CLI executable
- name: Make WP-CLI executable
  file:
    path: /tmp/wp-cli.phar
    mode: '0755'
  become: yes

# Move WP-CLI to /usr/local/bin
- name: Move WP-CLI to /usr/local/bin
  command: mv /tmp/wp-cli.phar /usr/local/bin/wp
  become: yes

# Verify WP-CLI installation
- name: Verify WP-CLI installation
  command: /usr/local/bin/wp --info
  register: wp_info
  ignore_errors: yes
  become: yes

# Debug WP-CLI information
- name: Display WP-CLI information
  debug:
    var: wp_info.stdout

# Install WordPress using WP-CLI
- name: Install WordPress using WP-CLI
  command: >
    /usr/local/bin/wp core install
    --url="http://wordpress4.yuvallab.xyz"
    --title="WordPress Site"
    --admin_user="yuval"
    --admin_password="{{ wp_admin_password }}"
    --admin_email="yuvalnix305@gmail.com"
    --path="/var/www/wordpress/wordpress"
  become: yes